@@layout('main')
    <div class="wrapper">
        <div class="row">
            <div class="col-md-10 col-md-push-1 col-md-pull-1">
                <div class="panel">
                    <header class="panel-heading dark">
                    <i class="fa fa-list"></i> Mettre à jour un utilisateur
                    </header>
                    <div class="panel-body">
                        <form method="POST" action="<?php echo context('url')->actual(); ?>" class="form-horizontal" role="form" id="crudForm">
                            <div class="form-group">
                                <label for="username" class="col-md-2 col-sm-2 control-label">Identifiant</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <input required type="text" name="username" id="username" value="<?php view()->show(view()->row['username']); ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="name" class="col-md-2 col-sm-2 control-label">Nom</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <input required type="text" name="name" id="name" value="<?php view()->show(view()->row['name']); ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="firstname" class="col-md-2 col-sm-2 control-label">Prénom</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <input required type="text" name="firstname" id="firstname" value="<?php view()->show(view()->row['firstname']); ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-md-2 col-sm-2 control-label">Email</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <input required type="email" name="email" id="email" value="<?php view()->show(view()->row['email']); ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="password" class="col-md-2 col-sm-2 control-label">Mot de passe</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <input required type="password" name="password" id="password" value="<?php view()->show(view()->row['password']); ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4 col-md-push-4 col-md-pull-4">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-check-square-o"></i> Valider
                                    </button>
                                    <button type="reset" class="btn btn-danger">
                                        <i class="fa fa-undo"></i> Annuler
                                    </button>
                                </div>
                            </div>
                            <a href="/crud/static/userlist" class="btn btn-success"><i class="fa fa-list"></i> Retour à la liste</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
