@@layout('main')
    <div class="wrapper">
        <div class="row">
            <div class="col-md-10 col-md-push-1 col-md-pull-1">
                <div class="panel">
                    <header class="panel-heading dark">
                    <i class="fa fa-list"></i> Mettre à jour une page
                    </header>
                    <div class="panel-body">
                        <form method="POST" action="<?php echo context('url')->actual(); ?>" class="form-horizontal" role="form" id="crudForm">
                            <div class="form-group">
                                <label for="html" class="col-md-2 col-sm-2 control-label">Contenu</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <textarea rows="6" class="form-control thinWysiwyg" name="html" id="html"><?php echo $v->htmlPage; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="config" class="col-md-2 col-sm-2 control-label">Configuration</label>
                                <div class="col-md-6 col-md-push-2 col-md-pull-2">
                                    <textarea rows="6" required class="form-control" name="config" id="config"><?php echo $v->configPage; ?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4 col-md-push-4 col-md-pull-4">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="fa fa-check-square-o"></i> Valider
                                    </button>
                                    <button type="reset" class="btn btn-danger">
                                        <i class="fa fa-undo"></i> Annuler
                                    </button>
                                </div>
                            </div>
                            <a href="/crud/static/pagelist" class="btn btn-success"><i class="fa fa-list"></i> Retour à la liste</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
