@@layout('main')
    <div class="wrapper">
        <div class="row">
            <div class="col-md-10 col-md-push-1 col-md-pull-1">
                <div class="panel panel-danger">
                    <header class="panel-heading">
                    <i class="fa fa-info fa-2x"></i> Informations
                    </header>
                    <div class="panel-body">
                        <div class="alert alert-danger col-md-8 col-md-push-2 col-md-pull-2">
                            Vous ne disposez pas des droits suffisants.<br />
                            Merci de contacter l'administrateur.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
