    <!--footer section start-->
    <footer class="sticky-footer">
        &copy; GP 1996 - 2014    </footer>
    <!--footer section end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<script src="/crud/assets/js/jquery-1.10.2.min.js"></script>
<script src="/crud/assets/js/jquery-ui-1.9.2.custom.min.js"></script>
<script src="/crud/assets/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/crud/assets/js/bootstrap.min.js"></script>
<script src="/crud/assets/js/modernizr.min.js"></script>
<script src="/crud/assets/js/jquery.nicescroll.js"></script>

<!--pickers plugins-->
<script type="text/javascript" src="/crud/assets/js/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/crud/assets/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="/crud/assets/js/bootstrap-daterangepicker/moment.min.js"></script>
<script type="text/javascript" src="/crud/assets/js/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="/crud/assets/js/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script type="text/javascript" src="/crud/assets/js/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>

<!--common scripts for all pages-->
<script src="/crud/assets/js/hover.js"></script>

<script type="text/javascript" src="/crud/assets/js/ckeditor/ckeditor.js"></script>
<!--pickers initialization-->
<script src="/crud/assets/js/pickers-init.js"></script>
<script src="/crud/assets/js/scripts.js"></script>

<script>
    jQuery(document).ready(function() {

        $('.crudDate').datepicker({
            language: 'fr_FR',
            weekStart: 1
        });
    });
</script>


</body>
</html>
