<?php
    namespace Thin;
    use \CrudBundle\Crud as c;

    return array(
        /* GENERAL SETTINGS */
        'singular'                  => 'Contact',
        'plural'                    => 'Contacts',
        'default_order'             => 'contact_id',
        'default_order_direction'   => 'ASC',
        'items_by_page'             => 25,
        'display'                   => false,
        'many'                      => array(),

        /* EVENTS */
        'before_create'             => false,
        'after_create'              => false,

        'before_read'               => false,
        'after_read'                => false,

        'before_update'             => false,
        'after_update'              => false,

        'before_delete'             => false,
        'after_delete'              => false,

        'before_list'               => false,
        'after_list'                => false,

        /* FIELDS */
        'fields'                    => array(
                        'contactsource_id' => array(
                'label' => 'Contactsource',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'owner_id' => array(
                'label' => 'Owner',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'contactstatus_id' => array(
                'label' => 'Contactstatus',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'date_add' => array(
                'label' => 'DateAdd',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'gender' => array(
                'label' => 'Gender',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'name' => array(
                'label' => 'Name',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'firstname' => array(
                'label' => 'Firstname',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'maidname' => array(
                'label' => 'Maidname',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'tel_home' => array(
                'label' => 'TelHome',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'tel_pro' => array(
                'label' => 'TelPro',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'tel_cell' => array(
                'label' => 'TelCell',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'email_pro' => array(
                'label' => 'EmailPro',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'email_home' => array(
                'label' => 'EmailHome',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'fax' => array(
                'label' => 'Fax',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'address' => array(
                'label' => 'Address',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'zipcode' => array(
                'label' => 'Zipcode',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'city' => array(
                'label' => 'City',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'birthdate' => array(
                'label' => 'Birthdate',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'birthplace' => array(
                'label' => 'Birthplace',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'maritalstatus_id' => array(
                'label' => 'Maritalstatus',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'personaldata' => array(
                'label' => 'Personaldata',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'workstatus_id' => array(
                'label' => 'Workstatus',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'workcontract_id' => array(
                'label' => 'Workcontract',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'work_age' => array(
                'label' => 'WorkAge',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'jobname' => array(
                'label' => 'Jobname',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'company' => array(
                'label' => 'Company',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'workdata' => array(
                'label' => 'Workdata',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'month_income' => array(
                'label' => 'MonthIncome',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'month_charge' => array(
                'label' => 'MonthCharge',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'debt' => array(
                'label' => 'Debt',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'saving_month' => array(
                'label' => 'SavingMonth',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'investment_duration' => array(
                'label' => 'InvestmentDuration',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'year_tax' => array(
                'label' => 'YearTax',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'holding' => array(
                'label' => 'Holding',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'financialdata' => array(
                'label' => 'Financialdata',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'couple_tax' => array(
                'label' => 'CoupleTax',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),
            'couple_holding' => array(
                'label' => 'CoupleHolding',
                'form_type' => 'text',
                'helper' => false,

                'required' => true,
                'is_listable' => true,
                'is_exportable' => true,
                'is_searchable' => true,
                'is_sortable' => true,
                'is_readable' => true,
                'is_creatable' => true,
                'is_updatable' => true,

                'content_view' => false,
                'content_list' => false,
                'content_search' => false,
                'content_create' => false,
            ),

        )
    );
