<?php view()->partial('header/classic.phtml'); ?>
<section id="content" class="container">
    <div class="row">
            <div class="col-md-offset-4 col-md-4">

                <img alt="" src="<?php echo container()->getUrlsite(); ?>assets/img/backend/key.svg" style="display: block; margin: 20px auto 40px; width: 100px;">

                <h3>Login</h3>

                <form action="" method="post">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="btn" type="submit"><span class="fui-mail"></span></button>
                            </span>
                            <input required type="text" id="pseudo" name="pseudo" placeholder="Your pseudo" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="btn" type="submit"><span class="fui-lock"></span></button>
                            </span>
                            <input required type="password" id="password" name="password" placeholder="Your password" class="form-control">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">Log me in please</button>

                </form>
                <p class="text-center margin-top-10">
                    <a href="<?php echo container()->getUrlsite(); ?>backend/password" class="small">Forgot your password?</a>
                </p>
            </div><!-- ./col-md-4 -->
        </div>
</section>
<?php view()->partial('footer/classic.phtml'); ?>
