<?php view()->partial('header/classic.phtml'); ?>
<section id="content" class="container">
    <div class="row">
            <div class="col-md-offset-4 col-md-4">

                <img alt="" src="<?php echo container()->getUrlsite(); ?>assets/img/backend/safe.svg" style="display: block; margin: 20px auto 40px; width: 100px;">

                <h3>recover password</h3>

                <p>Please enter your Email so we can send you an email to reset your password.</p>

                <form action="<?php echo container()->getUrlsite(); ?>backend/password" method="post">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <button class="btn" type="submit"><span class="fui-mail"></span></button>
                            </span>
                            <input required type="email" id="email" name="email" placeholder="Your email" class="form-control">
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block">Send reset email</button>

                </form>
            </div><!-- ./col-md-4 -->
        </div>
</section>
<?php view()->partial('footer/classic.phtml'); ?>
